### ISSUE TITLE
Add requeue socks dependency to Dockerfile for Thug 0.6.1 support

### ISSUE THREAD

**Issue by jjo-sec** [aikinci/thug#1]
Using the current Dockerfile (which will pull and build Thug 0.6.1) 

```
root@b2bd55d3ee0d:/opt/thug/src# python thug.py -h
Traceback (most recent call last):
  File "thug.py", line 24, in <module>
    from ThugAPI import *
  File "/opt/thug/src/ThugAPI/__init__.py", line 1, in <module>
    from .ThugAPI import ThugAPI
  File "/opt/thug/src/ThugAPI/ThugAPI.py", line 30, in <module>
    from DOM import Window, HTTPSession, DFT, MIMEHandler, SchemeHandler
  File "/opt/thug/src/DOM/Window.py", line 36, in <module>
    from .Navigator import Navigator
  File "/opt/thug/src/DOM/Navigator.py", line 36, in <module>
    from .HTTPSession import AboutBlank, FetchForbidden
  File "/opt/thug/src/DOM/HTTPSession.py", line 21, in <module>
    import requesocks
ImportError: No module named requesocks
```

Verified that adding requesocks to the pip install line fixes the issue 

```
root@1c4351bb0a4c:/opt/thug/src# python thug.py --version
Thug 0.6.1
```

I also experienced the same issue when pulling the latest from the honeynet docker registry, not sure if this is the right place to report that issue?

**Comment by aikinci** [comment]
Thanks. I have made the change the updated docker container should be up in a couple of minutes on the docker hub.

Cheers
